In [1]:
import numpy as np
import pandas as pd
import requests
from io import StringIO
import copy

url = "https://en.wikipedia.org/wiki/List_of_data_breaches"

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
}

response = requests.get(url, headers=headers)

html_io = StringIO(response.text)

tables = pd.read_html(html_io)

In [2]:
data1 = pd.DataFrame(tables[0])
data2 = pd.DataFrame(tables[1])

In [3]:
data1.head()

,Government,Agency,Year,Records,Organization type,Method,Sources
0,Netherlands,National Police Corps of the Netherlands,2024,"63,000+ staff members data including names, em...",police,hacked,[7]
1,United Kingdom,Transport for London,2024,5000+ Passengers data including home addresses...,Local Transport authority,hacked,[8]
2,50 companies and government institutions,Various,2022,6400000,various,poor security,[9][10]
3,California,California Department of Corrections and Rehab...,2022,"236,000 inmates personally identifiable inform...",government,CDCR denies any wrongdoing,https://www.cdcrdataclassactionsettlement.com/
4,India,Indian Council of Medical Research,2023,"815,000,000+, including Aadhaar IDs, passport ...",government,hacked by pwn0001,[11]

In [4]:
for columns in data1.columns:
    print(f'{columns} : {data1[columns].isna().sum()}')

Government : 0
Agency : 0
Year : 0
Records : 2
Organization type : 5
Method : 4
Sources : 2

In [5]:
data1.drop('Sources',axis=1,inplace=True)

In [6]:
data1.set_index('Year',inplace=True)

In [7]:
data1.sort_index(ascending=False,inplace=True)

In [8]:
data1['Government'].value_counts()

Government
United States                               22
United Kingdom                              12
Philippines                                  3
Pakistan                                     2
Various                                      2
Berkeley, California                         2
Texas, US                                    2
Singapore                                    2
Australia                                    2
Chile                                        2
United Nations                               2
?                                            2
Bangladesh                                   2
California                                   2
Indonesia                                    2
Norway                                       1
Cedar Rapids, Iowa                           1
Washington, US                               1
Miami, Florida                               1
South Carolina, US                           1
Greece                                       1
Salt Lake City, Utah                         1
Syrian government (Syria Files)              1
Milwaukee, Wisconsin                         1
Jefferson County, West Virginia              1
Massachusetts, US                            1
Virginia, US                                 1
San Francisco, California                    1
Stanford, California                         1
Oregon                                       1
Colorado, US                                 1
New Haven, Connecticut                       1
South Africa                                 1
Columbus, Ohio                               1
Puerto Rico                                  1
Florida                                      1
South Korea                                  1
College Park, Maryland                       1
Slovakia                                     1
England/Wales                                1
United Kingdom / Scotland                    1
Netherlands                                  1
India                                        1
Russia                                       1
Shanghai, China                              1
50 companies and government institutions     1
Ireland                                      1
New South Wales, AU                          1
Unknown                                      1
European Union                               1
Ecuador                                      1
Shah Alam, Malaysia                          1
Bulgaria                                     1
Argentina                                    1
London, UK                                   1
Sydney, Australia                            1
Orange County, Florida                       1
Sakai City, Japan                            1
Japan                                        1
Texas                                        1
Name: count, dtype: int64

In [9]:
invalid_values = ['50 companies and government institutions','?','Various','Unknown']
data1 = data1[~data1['Government'].isin(invalid_values)]

In [10]:
country_map = {
    'United States': 'USA',
    'California': 'USA',
    "Berkeley, California": 'USA',
    'Texas, US': 'USA',
    'Orange County, Florida': 'USA',
    'College Park, Maryland': 'USA',
    'Cedar Rapids, Iowa': 'USA',
    'Florida': 'USA',
    'Washington, US': 'USA',
    'South Carolina, US': 'USA',
    'San Francisco, California':'USA',
    'Massachusetts, US': 'USA',
    'Oregon': 'USA',
    'Milwaukee, Wisconsin': 'USA',
    'Colorado, US': 'USA',
    'Puerto Rico': 'USA',
    'Columbus, Ohio': 'USA',
    'Virginia, US': 'USA',
    'Stanford, California': 'USA',
    'Jefferson County, West Virginia':'USA',
    'Miami, Florida': 'USA',
    'Salt Lake City, Utah': 'USA',
    'Texas': 'USA',


    'United Kingdom': 'UK',
    'England/Wales': 'UK',
    'United Kingdom / Scotland': 'UK',
    'New Haven, Connecticut': 'UK',
    'London, UK' : 'UK',

    'Sydney, Australia' : 'Australia',
    'New South Wales, AU' : 'Australia',
    'Shanghai, China' : 'China',
    'Shah Alam, Malaysia' : 'Malaysia',
    'Sakai City, Japan' : 'Japan',
    "Syrian government (Syria Files)" : 'Syria'

}
new_data = copy.deepcopy(data1)
new_data['Government'] = new_data['Government'].replace(country_map)
new_data.rename(columns={'Government':'Country'},inplace=True)

In [11]:
new_data.head()

,Country,Agency,Records,Organization type,Method
Year,,,,,
2025,Pakistan,Federal Board of Revenue,"150 GB data containing CNICs, names, phone num...",financial,hacked
2025,Pakistan,Habib Bank Limited,"Employee records, bank account details, educat...",financial,hacked
2024,Australia,Western Sydney University,"7,500, including email accounts, SharePoint fi...",academic,hacked
2024,UK,Transport for London,5000+ Passengers data including home addresses...,Local Transport authority,hacked
2024,UK,England and Wales Cricket Board,43299,government,unknown

In [12]:
new_data['Organization type'] = new_data['Organization type'].fillna('Government')

In [13]:
new_data[new_data['Organization type']=='government, healthcare']

     Country    Agency Records       Organization type  Method
Year
2012     USA  Medicaid  780000  government, healthcare  hacked

In [14]:
new_data['Organization type'].value_counts().sum()

100

In [15]:
organisation_map = {
    # --- Government ---
    'government': 'Government',
    'law enforcement': 'Government',
    'police': 'Government',
    'bureau': 'Government',
    'political': 'Government',
    'politics': 'Government',
    'government, military': 'Military',
    'government, healthcare': 'Healthcare',

    # --- Academic ---
    'academic': 'Academic',

    # --- Healthcare ---
    'healthcare': 'Healthcare',
    'military, healthcare': 'Healthcare',

    # --- Financial ---
    'financial': 'Financial',

    # --- Military ---
    'military': 'Military',

    # --- Public / State-Owned ---
    'public broadcasting': 'Public',
    'special public corporation': 'Public',

    # --- Transport ---
    'local transport authority': 'Transport',
    'transport': 'Transport',

    # --- Technology / Telecom ---
    'telecom': 'Technology',
    'malware tools': 'Technology',
    'aerospace': 'Technology',

    # --- International ---
    'international': 'International'
}
new_data['Organization type'] = new_data['Organization type'].replace(organisation_map)

In [16]:
new_data['Organization type'].value_counts().sum()

100

In [17]:
new_data.head()

,Country,Agency,Records,Organization type,Method
Year,,,,,
2025,Pakistan,Federal Board of Revenue,"150 GB data containing CNICs, names, phone num...",Financial,hacked
2025,Pakistan,Habib Bank Limited,"Employee records, bank account details, educat...",Financial,hacked
2024,Australia,Western Sydney University,"7,500, including email accounts, SharePoint fi...",Academic,hacked
2024,UK,Transport for London,5000+ Passengers data including home addresses...,Local Transport authority,hacked
2024,UK,England and Wales Cricket Board,43299,Government,unknown

In [18]:
for columns in new_data.columns:
    print(f'{columns} : {new_data[columns].isna().sum()}')

Country : 0
Agency : 0
Records : 1
Organization type : 0
Method : 2

In [19]:
new_data['Method'].value_counts().sum()

98

In [20]:
breach_method_map = {
    # --- Hacking ---
    'hacked': 'Hacking',
    'cyber attack': 'Hacking',
    'hacked and published': 'Hacking',
    'hacked by pwn0001': 'Hacking',
    'hacked by v0g3lsec': 'Hacking',
    'hacked with a trojan': 'Hacking',
    'leaked and published': 'Hacking',

    # --- Insider Threat ---
    'inside job': 'Insider Threat',
    'internal job': 'Insider Threat',
    'insider': 'Insider Threat',
    'poor security/inside job': 'Insider Threat',

    # --- Misconfiguration / Poor Security ---
    'poor security': 'Misconfiguration',
    'misconfigured server': 'Misconfiguration',
    'unsecured database': 'Misconfiguration',
    'poor security / misconfigured server': 'Misconfiguration',
    'data leak due to security vulnerabilities': 'Misconfiguration',

    # --- Lost / Stolen ---
    'lost / stolen media': 'Lost / Stolen Device',
    'lost / stolen computer': 'Lost / Stolen Device',

    # --- Accidental ---
    'accidentally published': 'Accidental Exposure',

    # --- Ransomware ---
    'ransomware': 'Ransomware',

    # --- Unknown / Other ---
    'unknown': 'Other',
    'cdcr denies any wrongdoing': 'Other'
}

In [21]:
new_data['Method'] = (
    new_data['Method']
    .replace(breach_method_map)
    .fillna('Other')
)

In [22]:
counts = new_data['Organization type'].value_counts()
rare_categories = counts[counts < 5].index
new_data.loc[new_data['Organization type'].isin(rare_categories),'Organization type'] = 'Other'

In [23]:
counts = new_data['Method'].value_counts()
rare_categories2 = counts[counts < 5].index
new_data.loc[new_data['Method'].isin(rare_categories2),'Method'] = 'Other'

In [40]:
data1 = new_data
data1.head()

,Country,Agency,Records,Organization type,Method
Year,,,,,
2025,Pakistan,Federal Board of Revenue,"150 GB data containing CNICs, names, phone num...",Financial,Hacking
2025,Pakistan,Habib Bank Limited,"Employee records, bank account details, educat...",Financial,Hacking
2024,Australia,Western Sydney University,"7,500, including email accounts, SharePoint fi...",Academic,Hacking
2024,UK,Transport for London,5000+ Passengers data including home addresses...,Other,Hacking
2024,UK,England and Wales Cricket Board,43299,Government,Other

# Data 2

In [25]:
data2.set_index('Year',inplace=True)

In [26]:
data2 = data2.drop('Sources',axis=1)

In [27]:
data2.head()

,Entity,Records,Organization type,Method
Year,,,,
2022,50 companies and government institutions,6400000,various,poor security
2015,21st Century Oncology,"2,200,000 customer's data, including names, So...",healthcare,hacked
2023,23andMe,6900000,consumer genetics,credential stuffing
2020,500px,14870304,social network,hacked
2020,Accendo Insurance Co.,175350,healthcare,poor security

In [28]:
for columns in data2.columns:
    print(f'{columns} : {data2[columns].isna().sum()}')

Entity : 0
Records : 2
Organization type : 6
Method : 7

In [29]:
data2.sort_index(ascending=False,inplace=True)

In [30]:
data2['Organization type'].value_counts().sum()

368

In [31]:
industry_map = {
    # --- Technology ---
    'web': 'Technology',
    'tech': 'Technology',
    'information technology': 'Technology',
    'software': 'Technology',
    'hosting provider': 'Technology',
    'web services': 'Technology',
    'tech, web': 'Technology',
    'tech, cloud storage': 'Technology',
    'tech, data storage': 'Technology',
    'tech, marketing': 'Technology',
    'network monitoring': 'Technology',
    'information security': 'Technology',
    'security': 'Technology',
    'online': 'Technology',
    'local search': 'Technology',
    'question & answer': 'Technology',

    # --- Healthcare ---
    'healthcare': 'Healthcare',
    'pharmacy': 'Healthcare',
    'clinical laboratory': 'Healthcare',
    'consumer genetics': 'Healthcare',
    'healthcare, pharmacy': 'Healthcare',
    'healthcare, retail': 'Healthcare',

    # --- Financial ---
    'financial': 'Financial Services',
    'finance': 'Financial Services',
    'financial, credit reporting': 'Financial Services',
    'financial, credit bureau': 'Financial Services',
    'broker/dealer': 'Financial Services',
    'data broker': 'Financial Services',
    'data aggregator': 'Financial Services',
    'qr code payment': 'Financial Services',

    # --- Retail / E-commerce ---
    'retail': 'Retail & E-commerce',
    'shopping': 'Retail & E-commerce',
    'e-commerce': 'Retail & E-commerce',
    'electronics': 'Retail & E-commerce',
    'jewelry': 'Retail & E-commerce',
    'food': 'Retail & E-commerce',
    'restaurant': 'Retail & E-commerce',
    'hotel/casino': 'Retail & E-commerce',

    # --- Telecom ---
    'telecom': 'Telecom',
    'telecoms': 'Telecom',
    'telecommunications': 'Telecom',
    'mobile carrier': 'Telecom',
    'telephone directory': 'Telecom',

    # --- Media & Entertainment ---
    'media': 'Media & Entertainment',
    'publisher (magazine)': 'Media & Entertainment',
    'entertainment': 'Media & Entertainment',
    'social media/web': 'Media & Entertainment',

    # --- Gaming ---
    'gaming': 'Gaming',
    'gambling': 'Gaming',
    'web, gaming': 'Gaming',

    # --- Transport & Logistics ---
    'transport': 'Transport & Logistics',
    'logistics': 'Transport & Logistics',
    'ticket distribution': 'Transport & Logistics',
    'automotives': 'Transport & Logistics',

    # --- Energy ---
    'energy': 'Energy',

    # --- Education ---
    'educational services': 'Education',
    'private early-years education provider': 'Education',

    # --- Non-profit / Public ---
    'non-profit': 'Non-Profit / Public',
    'nonprofit, financial': 'Non-Profit / Public',
    'charity': 'Non-Profit / Public',
    'humanitarian': 'Non-Profit / Public',
    'arts group': 'Non-Profit / Public',

    # --- Social ---
    'social network': 'Social / Community',
    'dating': 'Social / Community'
}

In [32]:
data2['Organization type'] = (
    data2['Organization type']
    .replace(industry_map)
    .fillna('Other')
)

In [33]:
counts = data2['Organization type'].value_counts()
rare_categories2 = counts[counts < 5].index
data2.loc[data2['Organization type'].isin(rare_categories2),'Organization type'] = 'Other'

In [34]:
data2['Organization type'].value_counts().sum()

374

In [35]:
data2.head()

,Entity,Records,Organization type,Method
Year,,,,
2025,PANDORA,"name, birthdate, email address",Retail & E-commerce,hacked third party service
2025,Kido International,"Allegedly 8,000 children's and staff records e...",Other,cyberattack
2025,Discord,"Limited numbers of names, usernames, emails, I...",Social / Community,third-party customer support services hacked
2024,Cutout.Pro,19972829,Technology,hacked
2024,Roku,"15,363 accounts",Technology,credential stuffing attack

In [36]:
breach_method_map = {
    # --- HACKING ---
    'hacked': 'Hacking',
    'cyberattack': 'Hacking',
    'cyber infection/unautorized access': 'Hacking',
    'hacked by rhysida': 'Hacking',
    'hacked by alphv': 'Hacking',
    'hacked by lulzsec': 'Hacking',
    'hacked by russian hackers': 'Hacking',
    'hacked by latvian hackers': 'Hacking',
    'hacked third party service': 'Hacking',
    'hacked (phishing)': 'Hacking',
    'hacked with a trojan': 'Hacking',
    'hacked/misconfiguration': 'Hacking',
    'hacked / poor security': 'Hacking',
    'poor security / hacked': 'Hacking',
    'improper setting, hacked': 'Hacking',
    'maliciously injected javascript': 'Hacking',
    'maliciously modified javascript': 'Hacking',
    'vulnerabilities in plugins': 'Hacking',
    'zero-day vulnerabilities': 'Hacking',
    'vulnerability': 'Hacking',
    'web scraping': 'Hacking',
    '"unusual traffic"': 'Hacking',

    # --- CREDENTIAL COMPROMISE ---
    'compromised credentials': 'Credential Compromise',
    'credential stuffing': 'Credential Compromise',
    'credential stuffing attack': 'Credential Compromise',
    'stolen credentials': 'Credential Compromise',
    'compromised administrative account': 'Credential Compromise',
    'employee account compromise': 'Credential Compromise',
    'phishing attack': 'Credential Compromise',
    'social engineering': 'Credential Compromise',
    'poor security/account recovery': 'Credential Compromise',

    # --- MISCONFIGURATION ---
    'poor security': 'Misconfiguration',
    'misconfigured server': 'Misconfiguration',
    'misconfigured web server': 'Misconfiguration',
    'misconfigured website': 'Misconfiguration',
    'misconfigured api': 'Misconfiguration',
    'unprotected api': 'Misconfiguration',
    'unsecured s3 bucket': 'Misconfiguration',
    'publicly accessible amazon web services (aws) server': 'Misconfiguration',
    'data exposed by misconfiguration': 'Misconfiguration',
    'misconfiguration/poor security': 'Misconfiguration',
    'exposed test server': 'Misconfiguration',
    'system deficiency': 'Misconfiguration',

    # --- INSIDER THREAT ---
    'inside job': 'Insider Threat',
    'insider theft': 'Insider Threat',
    'rogue contractor': 'Insider Threat',
    'poor security/inside job': 'Insider Threat',
    'data misuse': 'Insider Threat',
    'intentionally selling data': 'Insider Threat',

    # --- LOST / STOLEN ---
    'lost / stolen media': 'Lost / Stolen Device',
    'lost / stolen computer': 'Lost / Stolen Device',
    'lost box of data tapes': 'Lost / Stolen Device',
    'discs found in trash': 'Lost / Stolen Device',
    'magnetic tape missing from an iron mountain incorporated storage facility': 'Lost / Stolen Device',
    'stolen laptop': 'Lost / Stolen Device',
    'lost/stolen device': 'Lost / Stolen Device',
    'intentionally lost': 'Lost / Stolen Device',

    # --- ACCIDENTAL ---
    'accidentally published': 'Accidental Exposure',
    'accidentally exposed': 'Accidental Exposure',
    'accidentally uploaded': 'Accidental Exposure',
    'accidentally published, (sometimes referred to as a "data valdez",[180][181][182] due to its size)': 'Accidental Exposure',

    # --- RANSOMWARE ---
    'ransomware hacked': 'Ransomware',
    'ransomware attack': 'Ransomware',
    'ransomware hacking': 'Ransomware',
    'ransomware/hacked': 'Ransomware',

    # --- OTHER / UNKNOWN ---
    'unknown': 'Other',
    'compilation of multiple data breaches': 'Other',
    'accessing certain databases containing customer information': 'Other',
    'data leak (12 nov. breachforums)': 'Other',
    'third-party customer support services hacked': 'Other',
    'brute force attack by a "dell partner"': 'Other'
}

data2['Method'] = (
    data2['Method']
    .replace(breach_method_map)
    .fillna('Other')
)

In [37]:
counts = data2['Method'].value_counts()
rare = counts[counts < 3].index

data2.loc[data2['Method'].isin(rare), 'Method'] = 'Other'

In [38]:
data2['Method'].value_counts()

Method
Hacking                  208
Misconfiguration          48
Other                     36
Lost / Stolen Device      34
Insider Threat            16
Credential Compromise     13
Accidental Exposure       12
Ransomware                 7
Name: count, dtype: int64

In [39]:
data2.head()

,Entity,Records,Organization type,Method
Year,,,,
2025,PANDORA,"name, birthdate, email address",Retail & E-commerce,Hacking
2025,Kido International,"Allegedly 8,000 children's and staff records e...",Other,Hacking
2025,Discord,"Limited numbers of names, usernames, emails, I...",Social / Community,Other
2024,Cutout.Pro,19972829,Technology,Hacking
2024,Roku,"15,363 accounts",Technology,Credential Compromise

In [41]:
# ===============================
# EXPORT CLEANED DATA TO CSV
# ===============================

# Make sure index (Year) is saved as a column
data1_csv = data1.reset_index()
data2_csv = data2.reset_index()

# Save to local directory
data1_csv.to_csv("data1_country_wise_breaches.csv", index=False)
data2_csv.to_csv("data2_company_wise_breaches.csv", index=False)

print("✅ CSV files created successfully:")
print(" - data1_country_wise_breaches.csv")
print(" - data2_company_wise_breaches.csv")

✅ CSV files created successfully:
 - data1_country_wise_breaches.csv
 - data2_company_wise_breaches.csv